import "../styles/globals.css";
import "../styles/checkmark-btn.scss";
import type { AppProps } from "next/app";
import Modal from "react-modal";
import Head from "next/head";
import { useEffect, useState } from "react";

import Layout from "./components/styling-divs/layout";
import { useShouldHydrate } from "./utils/should-hydrate";

// import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
// import { config } from "@fortawesome/fontawesome-svg-core";
// config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above

function MyApp({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  const requireAuthentication = pageProps.requireAuthentication;
  useEffect(() => {
    Modal?.setAppElement("#root");
  }, []);

  const { shouldHydrate } = useShouldHydrate();

  return (
    // <SessionProvider session={session}>
    <div id="root">
      <Head>
        <title>Gavekoordinator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gift-icon.ico" />
      </Head>
      <Layout>
        {shouldHydrate && <Component {...pageProps} />}
        {/* {requireAuthentication ? (
            <Auth>
              <Component {...pageProps} />
            </Auth>
          ) : (
            <Component {...pageProps} />
          )} */}
      </Layout>
    </div>
    // </SessionProvider>
  );
}

function Auth({ children }) {
  // if `{ required: true }` is supplied, `status` can only be "loading" or "authenticated"
  // const { status } = useSession({ required: true });

  // if (status === "loading") {
  //   return <div>Loading...</div>;
  // }

  return children;
}

export default MyApp;
