import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import mongoDB from '../sql-nodejs/cosmosdb/app'
import { removeDuplicateObjectsInArray } from '../utils/removeDuplicateObjectInArray'
import Button from './components/Buttons/Button'


const Home: NextPage = (props) => {

  const [userData, setUserData] = useState()
  const [createdLobbies, setCreatedLobbies] = useState([])
  const [belongingLobbies, setBelongingLobbies] = useState([])
  const router = useRouter();
  const db = new mongoDB
  const { data: session, status} = useSession()

  useEffect(() => {
    if(status === 'authenticated') {
      const dbResponse = async () => {
        const query = `SELECT * from c where c.creator = '${session.user.email}'`;
        const response = await db.read(query).then((data) => data.resources);
        setCreatedLobbies(response);
        const query2 = `SELECT c.id FROM c JOIN t in c.users WHERE t.email = '${session.user.email}'`;
        const response2 = await db.read(query2).then((data) => removeDuplicateObjectsInArray(data.resources));
        setBelongingLobbies(response2);

      }
      dbResponse()
    }
  },[])

  const onClick = (e) => {
    const val = e.currentTarget.innerHTML
    if (val === 'Join') {
      router.push('/join')
    } else if (val === 'Create') {
      router.push('/create')
    } else {
      console.error("dont mess with the DOM values bro")
    }

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex relative justify-center items-center h-full'>
        <div className='flex flex-col items-center  absolute top-0 right-8'>
          <h2>Lobbies you are part of</h2>
          <ul>
            {belongingLobbies.map((item, idx) => <li className='underline' key={idx}><Link key={idx} href={`lobby/${item.id}`}>{item.id}</Link></li> )}
          </ul>
        </div>
        <div>

        </div>
        <div>
          <h2 className='text-center'>Join or create a lobby !</h2>
          <div className='border-2'>
            <Button onClick={onClick} text={'Join'} />
            <Button onClick={onClick} text={'Create'} />
          </div>
        </div>
      </div>
    </>
  )
}

export default Home
